### ISSUE TITLE
The dataset

### ISSUE THREAD

**Issue by JegZheng** [frankkanis/CarND-Traffic-Sign-Classifier-Project#1]
Hi frank,

Thanks for your work in this project. I am quite interested about this work and recently I try to rerun it. Unfortunately I found the link of dataset seems to be invalid now. Could you please give another link to download the data? 

Cheers.

**Comment by frankkanis** [comment]
Hi,

you can download the dataset here: 
https://d17h27t6h515a5.cloudfront.net/topher/2017/February/5898cd6f_traffic-signs-data/traffic-signs-data.zip
or here:
http://video.udacity-data.com.s3.amazonaws.com/topher/2017/February/5898cd6f_traffic-signs-data/traffic-signs-data.zip

I downloaded the files 10 minutes ago, and both links worked for me. Maybe it was a temporary issue. Please try it again and let me know, if it still don't work for you.
